using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace pp3.dominio.Models
{
    public class Globals
    {
        public static string user = string.Empty;
        public enum CTSParentsMethods { ConsEcheqRegCta = 0, AnulacionCheque = 1, OtherFunction = 2 }

        public enum CodigosErrorCobisServices
        {
            Persona_Inexistente = 101043,
            CtaBco_Inexistente = 201005
        }
        public enum CodigosTareas
        {
            Clientes_Agregar = 0,
            Clientes_Eliminar = 1,
            Clientes_Modificar = 2,
            Clientes_VerReporte = 3,
            Cuentas_Agregar = 10,
            Cuentas_Eliminar = 11,
            Cuentas_Modificar = 12,
            Cuentas_VerReporte = 13,
            Rangos_Confirmar = 14,
            Firmas_Agregar = 20,
            Firmas_Eliminar = 21,
            Firmas_Modificar = 22,
            Firmas_VerReporte = 23,
            FirmantesPorCuenta_Agregar = 30,
            FirmantesPorCuenta_Eliminar = 31,
            FirmantesPorCuenta_Modificar = 32,
            FirmantesPorCuenta_VerReporte = 33,
            ModalidadesPago_Agregar = 40,
            ModalidadesPago_Eliminar = 41,
            ModalidadesPago_Modificar = 42,
            ModalidadesPago_VerReporte = 43,
            ModalidadesPago_EscComision = 44,
            ModalidadesPago_EscDescuento = 45,
            Beneficiarios_Agregar = 50,
            Beneficiarios_Eliminar = 51,
            Beneficiarios_Modificar = 52,
            Beneficiarios_VerReporte = 53,
            Beneficiarios_OrdenesPago = 54,
            OrdenesPago_Agregar = 60,
            OrdenesPago_Eliminar = 61,
            OrdenesPago_Modificar = 62,
            OrdenesPago_VerReporte = 63,
            OrdenesPago_Anulacion = 64,
            OrdenesPago_ImprimirRetencion = 65,
            TipoFolios_Agregar = 70,
            TipoFolios_Eliminar = 71,
            TipoFolios_Modificar = 72,
            TipoFolios_VerReporte = 73,
            Folios_Agregar = 80,
            Folios_Eliminar = 81,
            Folios_ModificarAnular = 82,
            Folios_VerReporte = 83,
            Folios_MarcarImpresos = 84,
            PerfilesUsuarios_Agregar = 90,
            PerfilesUsuarios_Eliminar = 91,
            PerfilesUsuarios_Modificar = 92,
            Tareas_Agregar = 100,
            Tareas_Eliminar = 101,
            Tareas_Modificar = 102,
            TareaPerfil_Prohibir = 110,
            TareaPerfil_Permitir = 111,
            Usuarios_VerReporte = 120,
            Usuarios_VerLog = 121,
            Usuarios_Agregar = 122,
            Usuarios_Eliminar = 123,
            Usuarios_Modificar = 124,
            ConsProveedores_Ver = 130,
            ConsProveedoresPorCliente_Ver = 131,
            ConsOrdenesPago_Ver = 132,
            EscalasComision_Agregar = 140,
            EscalasComision_Eliminar = 141,
            EscalasComision_Modificar = 142,
            EscalasDescuento_Agregar = 150,
            EscalasDescuento_Eliminar = 151,
            EscalasDescuento_Modificar = 152,
            ModCli_AltaMasivaPagos = 200,
            ModCli_AltaManualPagos = 201,
            ModCli_AltaMasivaBeneficiarios = 202,
            ModCli_AnulacionPagos = 203,
            ModCli_ConsultaOperadores = 204,
            ModCli_AltaOperador = 205,
            ModCli_BajaOperador = 206,
            ModCli_ModificacionOperador = 207,
            ModCli_ConsultaPagos = 208,
            ModCli_AutorizacionPagos = 209,
            ModCli_CambioClave = 210,
            ModCli_Login = 211,
            Sobres_Imprimir = 220,
            ReimpresionCheques = 230,
            AltaCodigoPostal = 231,
            BajaCodigoPostal = 232,
            ModificacionCodigoPostal = 233,
            AltaSucursal = 234,
            BajaSucursal = 235,
            ModificacionSucursal = 236,
            AltaMasivaBeneficiarios = 237,
            MigracionSucursalesCli = 238,
            MigracionSucursalesBnf = 239,
            ModificarSucursalEntrega = 240,
            AdministrarHorarioCorte = 241,
            A_RelSucursalModalidadPago = 242,
            B_RelSucursalModalidadPago = 243,
            A_RelTConvModalidadPago = 244,
            B_RelTConvModalidadPago = 245,
            M_RelTConvModalidadPago = 246,
            ReversarOrdenPago = 247,
            MarcaAcreditaConcentrador = 248,
            ReseteoEmisionCheques = 249,
            SucMigracion = 666,
        }
    }
}
